name: Python application

on:
    push:
        branches:
            - main
            

jobs:
    build: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/setup-python@v3

            - run: python exercise-2/main.py
            
        
